[platformio]
boards_dir = boards

[env:lilygo-t-rgb]
; tried a hundred different variations of src_dir, lib_extra_dirs, and build_src_filter
; to try to compile the ino file in the example folder and the src folder together
; but cannot escape linker errors.
; this workaround uses a script to create tmp.ino in the src folder
; tmp.ino has just a single line which is #include "../path-to-example.ino-file-given-in-custom_example_ino"
custom_example_ino = examples/OneEye_LILYGO_T_RGB_ST7701S/OneEye_LILYGO_T_RGB_ST7701S.ino

platform = espressif32
;board = esp32-s3-devkitc-1
board = LilyGo-T-RGB
framework = arduino

; this is specified in the board file for LilyGo-T-RGB
; if you are not using that board you will likely want to uncomment this
;board_build.arduino.memory_type = qio_opi

board_build.filesystem = fatfs
board_build.partitions = partitions_custom.csv
;board_build.partitions = partitions_custom_bigger_app.csv

upload_flags =
    --no-stub ; Upload Filesystem Image crashes before completing upload without this
    ;--before=no_reset

monitor_speed = 115200

; Hands-free software flashing and reset configurations
upload_resetmethod = nodemcu

; Remove the default size optimization flag
build_unflags = -Os

build_flags =
    -O2 ; -O3 results in slightly lower fps than -O2
    ;-flto ; fails to link

    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    -mfix-esp32-psram-cache-issue
    -D BOARD_BUILD_FLAGS_PSRAM_OPI=1

    -D ESP_PANEL_DRIVERS_BUS_ENABLE_RGB=1
    -D ESP_PANEL_BOARD_LCD_CONTROLLER=ST7701
    -D ESP_PANEL_LCD_ST7701_ENABLED=1

    ;-D MONSTER_EYES_LOG_LEVEL=0 ; to drop the strings entirely

    ;// use CONFIG_FILENAME to show one type of eye
    ;// use DEMO_MODE_SECONDS to show an random eye for N seconds, then load another random eye, and so on.
    ;// CONFIG_FILENAME and DEMO_MODE_SECONDS are mutually exclusive
    ;// if CONFIG_FILENAME is set it will override DEMO_MODE_SECONDS
    ;-D CONFIG_FILENAME=\"/pomni/config.eye\"
    ;-D CONFIG_FILENAME=\"/owl/config.eye\"
    ;-D CONFIG_FILENAME=\"/cat/config.eye\"
    ;-D CONFIG_FILENAME=\"/demon/config.eye\"
    -D DEMO_MODE_SECONDS=120 ; show a random eye for N seconds, load another andom eye, repeat

    -D EYELIDS_SYMMETRIC=1 ; 1 to override upperEyelid and lowerEyelid in config.eye and use upper-symmetrical.bmp and lower-symmetrical.bmp instead


lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.6
    moononournation/GFX Library for Arduino @ ^1.6.7
    adafruit/Adafruit SPIFlash @ ^5.1.1
    adafruit/SdFat - Adafruit Fork @ ^2.3.103
    adafruit/Adafruit TinyUSB Library @ ^3.7.7
    bblanchon/ArduinoJson @ ^7.4.3


extra_scripts =
    pre:copy_example.py
    generate_fatfs.py